---
- name: Ensure apt cache updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 600

- name: Ensure squid package installed
  ansible.builtin.package:
    name:
      - squid-openssl
      - squid-common
      - squidclient
    state: present

- name: Include configure tasks
  ansible.builtin.include_tasks: configure.yml
